# Generated by Django 5.2.3 on 2025-07-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("veteran", "Veteran"),
                    ("newbie", "Newbie"),
                ],
                default="newbie",
                max_length=50,
            ),
        ),
    ]
