# Generated by Django 5.2.3 on 2025-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
