# Generated by Django 5.2.3 on 2025-07-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-06-29"),
            preserve_default=False,
        ),
    ]
