# Generated by Django 5.2.3 on 2025-07-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
    ]
