# Generated by Django 5.2.3 on 2025-07-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("bg_color", models.CharField(default="bg-gray-600", max_length=20)),
                ("text_color", models.CharField(default="bg-gray-400", max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="users.tag"
            ),
        ),
    ]
