# Generated by Django 5.2.3 on 2025-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_tag_profile_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="text_color",
            field=models.CharField(default="text-gray-400", max_length=20),
        ),
    ]
