version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell < create_admin.py &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/0


  celery-worker:
    build: .
    command: celery -A itforum worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A itforum beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/0
volumes:
  pgdata:
