# Generated by Django 5.2.3 on 2025-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
