# Generated by Django 5.2.3 on 2025-07-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
