# Generated by Django 5.2.3 on 2025-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
