# Generated by Django 5.2.3 on 2025-07-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_postimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostImage",
        ),
    ]
