# Generated by Django 5.2.3 on 2025-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_delete_postimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/%Y/%m/%d"),
        ),
    ]
