# Generated by Django 5.2.3 on 2025-07-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="bg_color",
            field=models.CharField(default="bg-gray-600", max_length=20),
        ),
        migrations.AddField(
            model_name="category",
            name="text_color",
            field=models.CharField(default="text-gray-400", max_length=20),
        ),
    ]
