# Generated by Django 5.2.3 on 2025-08-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
